name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
    # Target platform
        platform: x64
    # Install Cygwin packages
        cygwin: 1
    # Enable static linking workaround
        static: 1
    # Set up cc/c++ executables
        cc: 1
    # On Cygwin, replace executable symlinks with hardlinks
        hardlinks: 0
        
    - run: build_nano-win.cmd
    
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
    # Artifact name
       name: Release
    # A file, directory or wildcard pattern that describes what to upload
       path: pkg_x86_64-w64-mingw32\bin
    # The desired behavior if no files are found using the provided path.

       if-no-files-found: ignore
       retention-days: 90
