name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

- name: Install MinGW
  uses: egor-tensin/setup-mingw@v2
    with:
    platform: x64
    
- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.1
  with:
    name:
    path: \pkg_x86_64-w64-mingw32\bin
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail
    if-no-files-found: ignore
    retention-days: 90
